### ISSUE TITLE
send images to ICEBERG

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/wv2-processing#29]
east FL to DJ
west FL to ICEBERG

**Comment by 7yl4r** [comment]
Loading images onto disk

```
# monroe
sent 433.60G bytes  received 120.27K bytes  7.66M bytes/sec
total size is 433.49G  speedup is 1.00
```

**Comment by bspitzbart** [comment]
I have transferred the Panhandle imagery to bridges over the network. I saw
between 6 and 37 MB/s.

**Comment by 7yl4r** [comment]
Looks like I'm getting around the same speed on my local setup. I'm not sure where the bottleneck is.

**Comment by bspitzbart** [comment]
I did a transfer from our local Seawulf machine with the same rsync command
and got 68 MB/s.
