### ISSUE TITLE
wv_classify_test.py error (seashell) 

### ISSUE THREAD

**Issue by lamchunying** [USF-IMARS/wv2-processing#31]
============================================= ERRORS ==============================================
________________________ ERROR collecting wv_classify/wv_classify_test.py _________________________
ImportError while importing test module '/home1/bellalam/XSEDE/git_workspace/imagery_utils/wv2-processing/wv_classify/wv_classify_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
wv_classify/wv_classify_test.py:4: in <module>
    from wv_classify.wv_classify import process_file
E   ImportError: cannot import name 'process_file'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================== 1 error in 1.25 seconds =====================================

**Comment by lamchunying** [comment]
wv2-processing 
pytest

**Comment by lamchunying** [comment]
======================================= test session starts =======================================
platform linux -- Python 3.6.7, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
rootdir: /home1/bellalam/XSEDE/git_workspace/imagery_utils/wv2-processing, inifile:
collected 3 items / 1 errors / 2 selected

**Comment by 7yl4r** [comment]
Can you try running pytest like this: `python -m pytest` instead of just `pytest`?

**Comment by lamchunying** [comment]
When I try` python -m pytest `
I receive `/usr/bin/python: No module named pytest`
even though I had `pip install pytest`

**Comment by 7yl4r** [comment]
This type of error can mean that you have multiple python installations; one pip is using and a different one when you call `python`.
To figure this out you can compare the output of `pip --version` and `python --version`.

The "gold standard" way to avoid things like this is to have a python installation just for this one project.
You may want to read through this article<https://docs.python-guide.org/dev/virtualenvs/> and play around with these tools a bit.
I'm only familiar with virtualenv myself but should probably learn the others.
________________________________
