### ISSUE TITLE
imagery_utils (seashell)

### ISSUE THREAD

**Issue by lamchunying** [USF-IMARS/wv2-processing#32]
Traceback (most recent call last):
  File "pgc_ortho.py", line 215, in <module>
    main()
  File "pgc_ortho.py", line 12, in main
    parent_parser, pos_arg_keys = ortho_functions.buildParentArgumentParser()
  File "/home1/bellalam/XSEDE/git_workspace/imagery_utils/lib/ortho_functions.py", line 274, in buildParentArgumentParser
    parser.add_argument("--version", action='version', version="imagery_utils v{}".format(utils.package_version))
ValueError: zero length field name in format

**Comment by lamchunying** [comment]
root: imagery_utils 
command: python pgc_ortho.py -p 4326 -c ns -t UInt16 -f GTiff \
> ./tests/testdata/ortho/WV02_20131005052802_10300100278D8500_13OCT05052802-P1BS-500099283010_01_P004.NTF \
> ./tests/output

**Comment by 7yl4r** [comment]
What is your working directory when running this command?
I'm running from the root of this repository and I get an error because it can't findpgy_ortho.py.

```
[tylar@tylar-xt3 wv2-processing]$ pwd
/home/tylar/git-repos/wv2-processing
[tylar@tylar-xt3 wv2-processing]$ python pgc_ortho.py -p 4326 -c ns -t UInt16 -f GTiff
python: can't open file 'pgc_ortho.py': [Errno 2] No such file or directory
```

**Comment by lamchunying** [comment]
This issue is for imagery_utils instead of w2-processing. Sorry for the confusion.
